### ISSUE TITLE
Submission for BioC 3.7

### ISSUE THREAD

**Issue by nhejazi** [wilsoncai1992/adaptest#34]
The package is now mostly ready to begin the process for submission to the [Bioconductor project](http://bioconductor.org/). The purpose of this issue is to keep track of changes that need to be made as we go through that submission process. For reference, documentation on the submission process is available [here](https://www.bioconductor.org/developers/package-submission/).

- [x] Open an issue at the [BioC contributions GitHub repo](https://github.com/Bioconductor/Contributions). Note that only the package owner (@wilsoncai1992) can start this process.
- [x] Create push hook for BioC contributions issue to track updates to branch `master` on this repo.
- [x] Update CRAN version of `origami` to 0.8.2+
- [x] Flesh out class definition for `adaptmle` and wrapper function `bioadaptest`
- [x] Complete vignette with examples from Bioconductor data sets

**Comment by wilsoncai1992** [comment]
The submission issue is made 

https://github.com/Bioconductor/Contributions/issues/628

**Comment by wilsoncai1992** [comment]
repost review

```

**Comment by wilsoncai1992** [comment]
report review 

DESCRIPTION
[] Use the release version of roxygen2
NAMESPACE
[]You may want to separate the "shinyprint" functionality into a different package?
R
[]Avoid using cryptic argument names, use names that are descriptives and helpful for the end user
[] The data_adapt class is based on a list which is not the best structure to use as you can't really enforce any validity checks to the components of the class as easily as you would with an S4 class.
[] Avoid the use of 1:n constructions
[] Use the allocate and fill method, e.g., ls <- vector("list", ncol(adaptY_composition))
[] Avoid using grep to find colnames in cv_param_est. Let the user provide the colname directly from the argument.
[] Replace sapply calls with the more robust vapply
[] You shouldn't need to "wrangle" the supported SummarizedExperiment class for your main function, it should just work with it as part of the integration process. In other words, it should make use of the SummarizedExperiment API rather than the assay(x); t(x) and rownames(x) <- colnames(x) <- NULL version.
[] A proper API should not use @ accessor functions. See: http://bioconductor.org/developers/how-to/efficient-code/
data
[] Provide descriptive names for your data,Y and A can mean anything.
vignette
[] It looks like you commented BiocStyle out.
[] Please add an installation chunk. It doesn't have to run.

**Comment by nhejazi** [comment]
Closing since the package has been accepted for BioC 3.7
